services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda,apigateway,cloudformation,iam,logs,ssm,sts,ecr
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"